[package]
name = "usrs-cli"
version = "0.1.0"
authors = ["Robin Nehls <git@manol.is>"]

[dependencies]
ultrastar-txt = "0.1"
gstreamer = "0.9"
log = "0.3"
env_logger = "0.4"
colored = "1.6"
clap = "2"
pitch_calc = "0.11"
portaudio = "0.7"
